version: "3.4"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 1.17

    privileged: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    volumes:
      - ..:/workspace:cached
      
    command: sleep infinity
