version: "3.4"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 1.20

    privileged: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    network_mode: service:mqtt

    volumes:
      - ..:/workspace:cached
      
    command: sleep infinity

  mqtt:
    image: eclipse-mosquitto:1.6
    restart: unless-stopped
